import { NextResponse } from 'next/server';
import type { OverviewResponse, DomainSummary, KPISummary, HealthStatus } from '@/types';
import { DEFAULT_DOMAINS } from '@/config/domains';

/**
 * GET /api/kpis/overview
 *
 * Returns aggregated KPI summaries for all domains.
 * This is the primary endpoint for the firm health dashboard landing page.
 */
export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const periodType = searchParams.get('periodType') || 'week';

  // Simulated KPIs for each domain
  const domainKPIs: Record<string, KPISummary[]> = {
    // Growth (BD)
    'd1000000-0000-0000-0000-000000000001': [
      {
        id: 'k-growth-1',
        processId: 'p1',
        name: 'Active Pipeline Value',
        shortName: 'Pipeline',
        unit: 'dollars',
        direction: 'higher_better',
        dataSource: 'notion',
        refreshCadence: 'weekly',
        displayFormat: 'currency',
        chartType: 'area',
        isPrimary: true,
        isActive: true,
        createdAt: '',
        updatedAt: '',
        targetValue: 2000000,
        latestValue: {
          id: 'v1',
          kpiDefinitionId: 'k-growth-1',
          periodStart: '2024-12-23',
          periodEnd: '2024-12-29',
          periodType: 'week',
          value: 2450000,
          status: 'healthy',
          trendDirection: 'up',
          ingestedAt: '',
        },
        sparklineData: [1800000, 1950000, 2100000, 2450000],
      },
      {
        id: 'k-growth-2',
        processId: 'p2',
        name: 'Win Rate',
        shortName: 'Win Rate',
        unit: 'percent',
        direction: 'higher_better',
        dataSource: 'notion',
        refreshCadence: 'quarterly',
        displayFormat: 'percent',
        chartType: 'line',
        isPrimary: true,
        isActive: true,
        createdAt: '',
        updatedAt: '',
        targetValue: 40,
        latestValue: {
          id: 'v2',
          kpiDefinitionId: 'k-growth-2',
          periodStart: '2024-10-01',
          periodEnd: '2024-12-31',
          periodType: 'quarter',
          value: 38,
          status: 'warning',
          trendDirection: 'down',
          ingestedAt: '',
        },
      },
      {
        id: 'k-growth-3',
        processId: 'p3',
        name: 'Active Opportunities',
        shortName: 'Opportunities',
        unit: 'count',
        direction: 'higher_better',
        dataSource: 'notion',
        refreshCadence: 'weekly',
        displayFormat: 'number',
        chartType: 'bar',
        isPrimary: true,
        isActive: true,
        createdAt: '',
        updatedAt: '',
        latestValue: {
          id: 'v3',
          kpiDefinitionId: 'k-growth-3',
          periodStart: '2024-12-23',
          periodEnd: '2024-12-29',
          periodType: 'week',
          value: 12,
          status: 'healthy',
          trendDirection: 'up',
          ingestedAt: '',
        },
      },
    ],

    // Service Delivery
    'd1000000-0000-0000-0000-000000000002': [
      {
        id: 'k-delivery-1',
        processId: 'p1',
        name: 'Active Engagements',
        shortName: 'Engagements',
        unit: 'count',
        direction: 'higher_better',
        dataSource: 'netsuite',
        refreshCadence: 'weekly',
        displayFormat: 'number',
        chartType: 'bar',
        isPrimary: true,
        isActive: true,
        createdAt: '',
        updatedAt: '',
        latestValue: {
          id: 'v4',
          kpiDefinitionId: 'k-delivery-1',
          periodStart: '2024-12-23',
          periodEnd: '2024-12-29',
          periodType: 'week',
          value: 8,
          status: 'healthy',
          trendDirection: 'flat',
          ingestedAt: '',
        },
      },
      {
        id: 'k-delivery-2',
        processId: 'p2',
        name: 'On-Time Delivery Rate',
        shortName: 'On-Time',
        unit: 'percent',
        direction: 'higher_better',
        dataSource: 'manual',
        refreshCadence: 'monthly',
        displayFormat: 'percent',
        chartType: 'bar',
        isPrimary: true,
        isActive: true,
        createdAt: '',
        updatedAt: '',
        targetValue: 95,
        latestValue: {
          id: 'v5',
          kpiDefinitionId: 'k-delivery-2',
          periodStart: '2024-12-01',
          periodEnd: '2024-12-31',
          periodType: 'month',
          value: 91,
          status: 'warning',
          trendDirection: 'down',
          ingestedAt: '',
        },
      },
      {
        id: 'k-delivery-3',
        processId: 'p3',
        name: 'Client Satisfaction',
        shortName: 'CSAT',
        unit: 'count',
        direction: 'higher_better',
        dataSource: 'manual',
        refreshCadence: 'quarterly',
        displayFormat: 'number',
        chartType: 'gauge',
        isPrimary: true,
        isActive: true,
        createdAt: '',
        updatedAt: '',
        targetValue: 4.5,
        latestValue: {
          id: 'v6',
          kpiDefinitionId: 'k-delivery-3',
          periodStart: '2024-10-01',
          periodEnd: '2024-12-31',
          periodType: 'quarter',
          value: 4.7,
          status: 'healthy',
          trendDirection: 'up',
          ingestedAt: '',
        },
      },
    ],

    // Contract Closure
    'd1000000-0000-0000-0000-000000000003': [
      {
        id: 'k-closure-1',
        processId: 'p1',
        name: 'Contracts Closed (Q4)',
        shortName: 'Closed',
        unit: 'count',
        direction: 'higher_better',
        dataSource: 'netsuite',
        refreshCadence: 'quarterly',
        displayFormat: 'number',
        chartType: 'bar',
        isPrimary: true,
        isActive: true,
        createdAt: '',
        updatedAt: '',
        latestValue: {
          id: 'v7',
          kpiDefinitionId: 'k-closure-1',
          periodStart: '2024-10-01',
          periodEnd: '2024-12-31',
          periodType: 'quarter',
          value: 5,
          status: 'healthy',
          trendDirection: 'up',
          ingestedAt: '',
        },
      },
      {
        id: 'k-closure-2',
        processId: 'p2',
        name: 'Avg Closeout Time',
        shortName: 'Closeout Days',
        unit: 'days',
        direction: 'lower_better',
        dataSource: 'manual',
        refreshCadence: 'quarterly',
        displayFormat: 'number',
        chartType: 'line',
        isPrimary: true,
        isActive: true,
        createdAt: '',
        updatedAt: '',
        targetValue: 14,
        latestValue: {
          id: 'v8',
          kpiDefinitionId: 'k-closure-2',
          periodStart: '2024-10-01',
          periodEnd: '2024-12-31',
          periodType: 'quarter',
          value: 18,
          status: 'warning',
          trendDirection: 'up',
          ingestedAt: '',
        },
      },
    ],

    // Finance
    'd1000000-0000-0000-0000-000000000004': [
      {
        id: 'k-finance-1',
        processId: 'p1',
        name: 'Days Sales Outstanding',
        shortName: 'DSO',
        unit: 'days',
        direction: 'lower_better',
        dataSource: 'netsuite',
        refreshCadence: 'monthly',
        displayFormat: 'number',
        chartType: 'line',
        isPrimary: true,
        isActive: true,
        createdAt: '',
        updatedAt: '',
        targetValue: 45,
        latestValue: {
          id: 'v9',
          kpiDefinitionId: 'k-finance-1',
          periodStart: '2024-12-01',
          periodEnd: '2024-12-31',
          periodType: 'month',
          value: 42,
          status: 'healthy',
          trendDirection: 'down',
          ingestedAt: '',
        },
      },
      {
        id: 'k-finance-2',
        processId: 'p2',
        name: 'AR 90+ Days',
        shortName: 'AR 90+',
        unit: 'dollars',
        direction: 'lower_better',
        dataSource: 'netsuite',
        refreshCadence: 'monthly',
        displayFormat: 'currency',
        chartType: 'bar',
        isPrimary: true,
        isActive: true,
        createdAt: '',
        updatedAt: '',
        targetValue: 0,
        warningThreshold: 50000,
        latestValue: {
          id: 'v10',
          kpiDefinitionId: 'k-finance-2',
          periodStart: '2024-12-01',
          periodEnd: '2024-12-31',
          periodType: 'month',
          value: 28500,
          status: 'healthy',
          trendDirection: 'down',
          ingestedAt: '',
        },
      },
      {
        id: 'k-finance-3',
        processId: 'p3',
        name: 'Monthly Revenue',
        shortName: 'Revenue',
        unit: 'dollars',
        direction: 'higher_better',
        dataSource: 'netsuite',
        refreshCadence: 'monthly',
        displayFormat: 'currency',
        chartType: 'area',
        isPrimary: true,
        isActive: true,
        createdAt: '',
        updatedAt: '',
        latestValue: {
          id: 'v11',
          kpiDefinitionId: 'k-finance-3',
          periodStart: '2024-12-01',
          periodEnd: '2024-12-31',
          periodType: 'month',
          value: 485000,
          status: 'healthy',
          trendDirection: 'up',
          ingestedAt: '',
        },
      },
    ],

    // Internal Operations
    'd1000000-0000-0000-0000-000000000005': [
      {
        id: 'k-ops-1',
        processId: 'p1',
        name: 'Harvest Compliance',
        shortName: 'Compliance',
        unit: 'percent',
        direction: 'higher_better',
        dataSource: 'excel_harvest',
        refreshCadence: 'weekly',
        displayFormat: 'percent',
        chartType: 'bar',
        isPrimary: true,
        isActive: true,
        createdAt: '',
        updatedAt: '',
        targetValue: 95,
        latestValue: {
          id: 'v12',
          kpiDefinitionId: 'k-ops-1',
          periodStart: '2024-12-23',
          periodEnd: '2024-12-29',
          periodType: 'week',
          value: 94,
          status: 'healthy',
          trendDirection: 'up',
          ingestedAt: '',
        },
        sparklineData: [82, 88, 91, 94],
      },
      {
        id: 'k-ops-2',
        processId: 'p2',
        name: 'Training Completion',
        shortName: 'Training',
        unit: 'percent',
        direction: 'higher_better',
        dataSource: 'excel_training',
        refreshCadence: 'monthly',
        displayFormat: 'percent',
        chartType: 'bar',
        isPrimary: true,
        isActive: true,
        createdAt: '',
        updatedAt: '',
        targetValue: 100,
        latestValue: {
          id: 'v13',
          kpiDefinitionId: 'k-ops-2',
          periodStart: '2024-12-01',
          periodEnd: '2024-12-31',
          periodType: 'month',
          value: 88,
          status: 'warning',
          trendDirection: 'up',
          ingestedAt: '',
        },
      },
      {
        id: 'k-ops-3',
        processId: 'p3',
        name: 'Billable Utilization',
        shortName: 'Utilization',
        unit: 'percent',
        direction: 'higher_better',
        dataSource: 'excel_billable',
        refreshCadence: 'weekly',
        displayFormat: 'percent',
        chartType: 'line',
        isPrimary: true,
        isActive: true,
        createdAt: '',
        updatedAt: '',
        targetValue: 75,
        latestValue: {
          id: 'v14',
          kpiDefinitionId: 'k-ops-3',
          periodStart: '2024-12-23',
          periodEnd: '2024-12-29',
          periodType: 'week',
          value: 72,
          status: 'warning',
          trendDirection: 'down',
          ingestedAt: '',
        },
      },
    ],

    // Board & CSOG
    'd1000000-0000-0000-0000-000000000006': [
      {
        id: 'k-board-1',
        processId: 'p1',
        name: 'Strategic Initiatives',
        shortName: 'Initiatives',
        unit: 'count',
        direction: 'higher_better',
        dataSource: 'manual',
        refreshCadence: 'quarterly',
        displayFormat: 'number',
        chartType: 'bar',
        isPrimary: true,
        isActive: true,
        createdAt: '',
        updatedAt: '',
        latestValue: {
          id: 'v15',
          kpiDefinitionId: 'k-board-1',
          periodStart: '2024-10-01',
          periodEnd: '2024-12-31',
          periodType: 'quarter',
          value: 6,
          status: 'healthy',
          trendDirection: 'flat',
          ingestedAt: '',
        },
      },
      {
        id: 'k-board-2',
        processId: 'p2',
        name: 'On-Track Initiatives',
        shortName: 'On-Track',
        unit: 'percent',
        direction: 'higher_better',
        dataSource: 'manual',
        refreshCadence: 'monthly',
        displayFormat: 'percent',
        chartType: 'gauge',
        isPrimary: true,
        isActive: true,
        createdAt: '',
        updatedAt: '',
        targetValue: 80,
        latestValue: {
          id: 'v16',
          kpiDefinitionId: 'k-board-2',
          periodStart: '2024-12-01',
          periodEnd: '2024-12-31',
          periodType: 'month',
          value: 83,
          status: 'healthy',
          trendDirection: 'up',
          ingestedAt: '',
        },
      },
    ],
  };

  // Calculate overall status based on KPIs
  const calculateOverallStatus = (kpis: KPISummary[]): HealthStatus => {
    if (kpis.some(k => k.latestValue?.status === 'critical')) return 'critical';
    if (kpis.some(k => k.latestValue?.status === 'warning')) return 'warning';
    return 'healthy';
  };

  const domains: DomainSummary[] = DEFAULT_DOMAINS.map((domain) => {
    const kpis = domainKPIs[domain.id!] || [];
    return {
      ...domain,
      id: domain.id!,
      name: domain.name!,
      shortName: domain.shortName!,
      displayOrder: domain.displayOrder!,
      colorHex: domain.colorHex!,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      processes: [],
      primaryKpis: kpis,
      overallStatus: calculateOverallStatus(kpis),
      activeGapsCount: domain.id === 'd1000000-0000-0000-0000-000000000005' ? 2 :
                       domain.id === 'd1000000-0000-0000-0000-000000000002' ? 1 :
                       domain.id === 'd1000000-0000-0000-0000-000000000003' ? 1 : 0,
    };
  });

  const response: OverviewResponse = {
    domains,
    filters: {
      timeFilter: {
        periodType: periodType as 'week' | 'month' | 'quarter',
        periodsBack: 4,
      },
    },
    lastUpdated: new Date().toISOString(),
  };

  return NextResponse.json(response);
}
