// Names match BambooHR employee directory
export const EMPLOYEES: string[] = [
  "Caleb Allen",
  "Erica Bauer",
  "Jessica Casebolt",
  "Jordana Choucair",
  "Ashley DeGarmo",
  "Elveena Fareedi",
  "Christopher Hart",
  "Alexander Hryhorczuk",
  "Tanner Johnson",
  "Chris Kalvig",
  "Mindy Klowden",
  "Cheryl Matochik",
  "Mark Nemelka",
  "Topher Rasmussen",
  "Lindsay Reeves",
  "Timothy Rourke",
  "Robert Schenck",
  "Courtney Shammas",
  "Jenna Slusarz",
  "Dacia Smith",
  "David Smith",
  "Aisha Waheed",
  "Gregory Williams",
  "Andy Wilson",
];
